#!/bin/bash
#Este script permite hacer un backup del Fallout Shelter desde un móvil Android a un sistema Ubuntu.

#Primera parte: declarar las rutas necesarias para evitar pringar demasiado el script
prima=/run/user/1000/gvfs
secunda=home/$USER/Desktop/FShelterBackup
#Segunda parte: búsqueda y guardado de la ruta del móvil.
echo "Buscando dispositivo..."
cd /
cd $prima
tercia="$(echo *)"
#Tercera parte: enrutado hasta la carpeta objetivo
cd $prima/$tercia
cuarta="$(echo *)"
#Esto parece una tontería, pero me garantiza llegar si el dispositivo estuviera en otro idioma. El resto de la ruta es igual.
cd "$cuarta/Android/data"
echo "Dispositivo encontrado. Copiando archivos de juego..."
cp -R com.bethsoft.falloutshelter/ /$secunda/com.bethsoft.falloutshelter-$(date +"%A-%d-%m-%Y-%r")
echo "He terminado. Hasta pronto"
sleep 2
